### ISSUE TITLE
YouTube Alerts is broken

### ISSUE THREAD

**Issue by DerpyChap** [nerdcubed/n3bot-issues#2]
**Your Discord Name:** DerpyChap#7162

**This is a: (select one)**
- [x] Bug
- [ ] Feature Request 

**Please describe in detail the issue or the request:**
```
YES WE KNOW THIS IS BROKEN ALREADY, WE ARE WORKING ON IT
```

**Comment by luludotdev** [comment]
fixed now nice

**Comment by DerpyChap** [comment]
nice
